### ISSUE TITLE
Any rss or web push notification?

### ISSUE THREAD

**Issue by glazec** [random-yang/random-yang.github.io#1]
我很喜欢你的博客内容。提供RSS订阅或者浏览器通知推送功能么？

**Comment by random-yang** [comment]
@glazec 抱歉，这个仓库平时不怎么查看issues，如果您有rss订阅的需要，我会考虑加rss，麻烦你耐心等待一下了，OK了我会通过这个issue通知你的。感谢你的欣赏支持，后期我会努力记录更高质量的blog内容。

**Comment by glazec** [comment]
好的谢谢呢。

**Comment by random-yang** [comment]
@glazec 你好，Rss已经添加了
1. 右键
2. 拷贝
3. 通过你自己的Rss客户端订阅这个链接即可
<img width="535" alt="image" src="https://user-images.githubusercontent.com/25839518/76137973-bad63380-607d-11ea-9439-9f1b6122f1ee.png">

**Comment by glazec** [comment]
谢谢
